<script lang="ts">
	import Entry from '$lib/components/Entry.svelte';
	import PageHeader from '$lib/components/PageHeader.svelte';
	import TT from '$lib/components/ToolTip.svelte';
	import FN from '$lib/components/Footnote.svelte';

	let footnotes: Array<string> = ['hello world'];
</script>

<PageHeader>Effects of Pollution</PageHeader>

<Entry bind:footnotes id="8.7mill">
	<span slot="num">8.7 million</span>
	<span slot="lead"
		>Globally, an estimated 8,700,000 premature deaths each year are caused by the fossil fuel
		component of fine particulate matter <TT
			tt={[
				'(PM<sub>2.5</sub>)',
				'Particulate matter with an aerodynamic diameter of less than 2.5&micro;m.'
			]}
		/> due to the burning of fossil-fuels <FN
			{footnotes}
			desc="'Global mortality from outdoor fine particle pollution generated by fossil fuel combustion'"
			accessed="18th November, 2023"
			url="https://www.sciencedirect.com/science/article/abs/pii/S0013935121000487"
		/>.
	</span>
	<ul>
		<li>
			The worst affected areas are India (2.5 million deaths), China (2.4 million deaths) and parts
			of the eastern US, Europe and Southeast Asia. Due to a 43.7% reduction in fossil fuel PM<sub
				>2.5</sub
			> between 2012 and 2018 in China, premature deaths dropped from the previously estimated 3.9 million.
		</li>
		<li>
			Children breathe more air relative to their body weight and are exposed to more pollutants. In
			2012, 169,000 deaths of children under the age of 5 were due to PM<sub>2.5</sub> including dust
			and wildfire smoke (not fossil fuels alone).
		</li>
		<li>
			The figures quoted above relate to 2018, when there were 57.4 million deaths worldwide <FN
				{footnotes}
				desc="'Deaths per year'"
				accessed="18th November, 2023"
				url="https://ourworldindata.org/grapher/number-of-deaths-per-year"
			/> so 1 in 6.6 deaths worldwide were premature. And premature because of fossil fuel pollution.
			(Other estimates, from University Colleg London, suggest a higher impact <FN
				{footnotes}
				desc="'Fossil fuel air pollution responsible for 1 in 5 deaths worldwide'"
				accessed="18th November, 2023"
				url="https://www.ucl.ac.uk/news/2021/feb/fossil-fuel-air-pollution-responsible-1-5-deaths-worldwide"
			/>.)
		</li>
	</ul>
</Entry>
